# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teap_report_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1316, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setEnabled(True)
        self.tabWidgetMain.setTabsClosable(False)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitterCategoryOverview = QtWidgets.QSplitter(self.tab_2)
        self.splitterCategoryOverview.setOrientation(QtCore.Qt.Horizontal)
        self.splitterCategoryOverview.setChildrenCollapsible(False)
        self.splitterCategoryOverview.setObjectName("splitterCategoryOverview")
        self.MplWidgetCategoryOverview = MplWidget(self.splitterCategoryOverview)
        self.MplWidgetCategoryOverview.setObjectName("MplWidgetCategoryOverview")
        self.tableViewCategoryOverview = QtWidgets.QTableView(self.splitterCategoryOverview)
        self.tableViewCategoryOverview.setObjectName("tableViewCategoryOverview")
        self.verticalLayout_6.addWidget(self.splitterCategoryOverview)
        self.tabWidgetMain.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.comboBoxSubmissionFilter = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxSubmissionFilter.setObjectName("comboBoxSubmissionFilter")
        self.horizontalLayout_5.addWidget(self.comboBoxSubmissionFilter)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.comboBoxGradingFilter = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxGradingFilter.setObjectName("comboBoxGradingFilter")
        self.horizontalLayout_5.addWidget(self.comboBoxGradingFilter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.tableViewModules = QtWidgets.QTableView(self.tab_3)
        self.tableViewModules.setObjectName("tableViewModules")
        self.verticalLayout_7.addWidget(self.tableViewModules)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.textEditCompetencyFeedback = QtWidgets.QTextEdit(self.tab_3)
        self.textEditCompetencyFeedback.setReadOnly(True)
        self.textEditCompetencyFeedback.setObjectName("textEditCompetencyFeedback")
        self.horizontalLayout_4.addWidget(self.textEditCompetencyFeedback)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidgetMain.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxOverviewPlotRelative = QtWidgets.QCheckBox(self.tab_4)
        self.checkBoxOverviewPlotRelative.setChecked(True)
        self.checkBoxOverviewPlotRelative.setObjectName("checkBoxOverviewPlotRelative")
        self.verticalLayout_4.addWidget(self.checkBoxOverviewPlotRelative)
        self.MplWidgetOverview = MplWidget(self.tab_4)
        self.MplWidgetOverview.setObjectName("MplWidgetOverview")
        self.verticalLayout_4.addWidget(self.MplWidgetOverview)
        self.tabWidgetMain.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBoxTEAPLength = QtWidgets.QComboBox(self.tab_6)
        self.comboBoxTEAPLength.setObjectName("comboBoxTEAPLength")
        self.horizontalLayout_2.addWidget(self.comboBoxTEAPLength)
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.dateEditProgramStart = QtWidgets.QDateEdit(self.tab_6)
        self.dateEditProgramStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditProgramStart.setObjectName("dateEditProgramStart")
        self.horizontalLayout_2.addWidget(self.dateEditProgramStart)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.MplWidgetTracking = MplWidget(self.tab_6)
        self.MplWidgetTracking.setObjectName("MplWidgetTracking")
        self.verticalLayout_5.addWidget(self.MplWidgetTracking)
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBoxShowPlan = QtWidgets.QCheckBox(self.tab_6)
        self.checkBoxShowPlan.setObjectName("checkBoxShowPlan")
        self.horizontalLayout_6.addWidget(self.checkBoxShowPlan)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.dateEditPlanStart = QtWidgets.QDateEdit(self.tab_6)
        self.dateEditPlanStart.setCalendarPopup(True)
        self.dateEditPlanStart.setObjectName("dateEditPlanStart")
        self.horizontalLayout_6.addWidget(self.dateEditPlanStart)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.dateEditPlanEnd = QtWidgets.QDateEdit(self.tab_6)
        self.dateEditPlanEnd.setCalendarPopup(True)
        self.dateEditPlanEnd.setObjectName("dateEditPlanEnd")
        self.horizontalLayout_6.addWidget(self.dateEditPlanEnd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBoxShowExtrapolation = QtWidgets.QCheckBox(self.tab_6)
        self.checkBoxShowExtrapolation.setObjectName("checkBoxShowExtrapolation")
        self.horizontalLayout_7.addWidget(self.checkBoxShowExtrapolation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.spinBoxMonthsToExtrapolate = QtWidgets.QSpinBox(self.tab_6)
        self.spinBoxMonthsToExtrapolate.setMinimum(1)
        self.spinBoxMonthsToExtrapolate.setProperty("value", 6)
        self.spinBoxMonthsToExtrapolate.setObjectName("spinBoxMonthsToExtrapolate")
        self.horizontalLayout_7.addWidget(self.spinBoxMonthsToExtrapolate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidgetMain.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.labelPartialSignedOffCompetencies = QtWidgets.QLabel(self.tab_5)
        self.labelPartialSignedOffCompetencies.setObjectName("labelPartialSignedOffCompetencies")
        self.gridLayout.addWidget(self.labelPartialSignedOffCompetencies, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.labelSignedOffCompetencies = QtWidgets.QLabel(self.tab_5)
        self.labelSignedOffCompetencies.setObjectName("labelSignedOffCompetencies")
        self.gridLayout.addWidget(self.labelSignedOffCompetencies, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.labelNonSignedOffCompetencies = QtWidgets.QLabel(self.tab_5)
        self.labelNonSignedOffCompetencies.setObjectName("labelNonSignedOffCompetencies")
        self.gridLayout.addWidget(self.labelNonSignedOffCompetencies, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.labelAverageWaitingTimeForSignOff = QtWidgets.QLabel(self.tab_5)
        self.labelAverageWaitingTimeForSignOff.setObjectName("labelAverageWaitingTimeForSignOff")
        self.gridLayout.addWidget(self.labelAverageWaitingTimeForSignOff, 6, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        self.labelWaitingOnGradingCompetencies = QtWidgets.QLabel(self.tab_5)
        self.labelWaitingOnGradingCompetencies.setObjectName("labelWaitingOnGradingCompetencies")
        self.gridLayout.addWidget(self.labelWaitingOnGradingCompetencies, 4, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.tabWidgetMain.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditCometUsername = QtWidgets.QLineEdit(self.tab_7)
        self.lineEditCometUsername.setObjectName("lineEditCometUsername")
        self.horizontalLayout.addWidget(self.lineEditCometUsername)
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditCometPassword = QtWidgets.QLineEdit(self.tab_7)
        self.lineEditCometPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditCometPassword.setObjectName("lineEditCometPassword")
        self.horizontalLayout.addWidget(self.lineEditCometPassword)
        self.pushButtonLoadPreviousData = QtWidgets.QPushButton(self.tab_7)
        self.pushButtonLoadPreviousData.setObjectName("pushButtonLoadPreviousData")
        self.horizontalLayout.addWidget(self.pushButtonLoadPreviousData)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBoxCachedData = QtWidgets.QComboBox(self.tab_7)
        self.comboBoxCachedData.setObjectName("comboBoxCachedData")
        self.horizontalLayout_3.addWidget(self.comboBoxCachedData)
        self.pushButtonLoadSelectedCachedFile = QtWidgets.QPushButton(self.tab_7)
        self.pushButtonLoadSelectedCachedFile.setObjectName("pushButtonLoadSelectedCachedFile")
        self.horizontalLayout_3.addWidget(self.pushButtonLoadSelectedCachedFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidgetMain.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidgetMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1316, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Assuming brachy level 2"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_2), _translate("MainWindow", "Category Overview"))
        self.label_16.setText(_translate("MainWindow", "Submission status"))
        self.label_15.setText(_translate("MainWindow", "Grading status"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_3), _translate("MainWindow", "Scores"))
        self.checkBoxOverviewPlotRelative.setText(_translate("MainWindow", "Relative completion"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_4), _translate("MainWindow", "Module Overview"))
        self.label_7.setText(_translate("MainWindow", "Length of program"))
        self.label_10.setText(_translate("MainWindow", "Start of program"))
        self.label_14.setText(_translate("MainWindow", "Note that \'Uploaded\' points assumes any competency that is waiting for grading has had all the work done to sign it off completely"))
        self.checkBoxShowPlan.setText(_translate("MainWindow", "Show plan"))
        self.label_18.setText(_translate("MainWindow", "Start"))
        self.dateEditPlanStart.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_19.setText(_translate("MainWindow", "Finish"))
        self.dateEditPlanEnd.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.checkBoxShowExtrapolation.setText(_translate("MainWindow", "Show extrapolation"))
        self.label_17.setText(_translate("MainWindow", "Months to use for extrapolation"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_6), _translate("MainWindow", "Tracking"))
        self.label_9.setText(_translate("MainWindow", "Non-signed off competencies"))
        self.label_11.setText(_translate("MainWindow", "Waiting on grading"))
        self.labelPartialSignedOffCompetencies.setText(_translate("MainWindow", "0 [%]"))
        self.label_13.setText(_translate("MainWindow", "Average time between upload and sign off*"))
        self.labelSignedOffCompetencies.setText(_translate("MainWindow", "0 [%]"))
        self.label_3.setText(_translate("MainWindow", "Fully signed off competencies"))
        self.labelNonSignedOffCompetencies.setText(_translate("MainWindow", "0 [%]"))
        self.label_6.setText(_translate("MainWindow", "Partial signed off competencies"))
        self.labelAverageWaitingTimeForSignOff.setText(_translate("MainWindow", "0 days"))
        self.labelWaitingOnGradingCompetencies.setText(_translate("MainWindow", "0 [%]"))
        self.label_12.setText(_translate("MainWindow", "*This is calculated as mean time between last modified date and date graded"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_5), _translate("MainWindow", "Misc"))
        self.label_4.setText(_translate("MainWindow", "Load new data from COMET"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.pushButtonLoadPreviousData.setText(_translate("MainWindow", "Get from Comet"))
        self.label_5.setText(_translate("MainWindow", "Load previously saved data"))
        self.pushButtonLoadSelectedCachedFile.setText(_translate("MainWindow", "Load"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_7), _translate("MainWindow", "Get data"))
from widgets.MplWidget import MplWidget
